// <auto-generated />
using System;
using Car_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Car_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260305000000_AddChatMessageReadAt")]
    partial class AddChatMessageReadAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Car_Project.Models.AppUser", b =>
                {
                    b.Property<string>("Id").HasColumnType("nvarchar(450)");
                    b.Property<int>("AccessFailedCount").HasColumnType("int");
                    b.Property<string>("AvatarUrl").HasColumnType("nvarchar(max)");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedDate").HasColumnType("datetime2");
                    b.Property<string>("Email").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<bool>("EmailConfirmed").HasColumnType("bit");
                    b.Property<string>("FullName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<bool>("LockoutEnabled").HasColumnType("bit");
                    b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("datetimeoffset");
                    b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("PasswordHash").HasColumnType("nvarchar(max)");
                    b.Property<string>("PhoneNumber").HasColumnType("nvarchar(max)");
                    b.Property<bool>("PhoneNumberConfirmed").HasColumnType("bit");
                    b.Property<string>("SecurityStamp").HasColumnType("nvarchar(max)");
                    b.Property<bool>("TwoFactorEnabled").HasColumnType("bit");
                    b.Property<string>("UserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
                    b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex").HasFilter("[NormalizedUserName] IS NOT NULL");
                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Car_Project.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<bool>("IsRead").HasColumnType("bit");
                    b.Property<string>("Message").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("ReadAt").HasColumnType("datetime2");
                    b.Property<string>("ReceiverId").HasColumnType("nvarchar(450)");
                    b.Property<string>("SenderId").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<string>("SenderName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("SentAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("ReceiverId");
                    b.HasIndex("SenderId");
                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Car_Project.Models.ChatMessage", b =>
                {
                    b.HasOne("Car_Project.Models.AppUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict);
                    b.HasOne("Car_Project.Models.AppUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("Receiver");
                    b.Navigation("Sender");
                });
#pragma warning restore 612, 618
        }
    }
}
